apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:example@mongodb:27017/?authSource=admin"
  JWT_SECRET_KEY: "0/ivh8N6c54T27LyYirxrRRXkX7ikT+ZSjY9Pa1q+no="
